ARG IMAGE_NAME
FROM ${IMAGE_NAME}:temp AS image

RUN GOLANG_VERSION=1.23.8 \
    && DIGEST='45b87381172a58d62c977f27c4683c8681ef36580abecd14fd124d24ca306d3f' \
    && wget -O go.tgz "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
    && echo "${DIGEST} *go.tgz" | sha256sum -c - \
    &&	tar -C /usr/local -xzf go.tgz \
    && rm go.tgz \
    && echo PATH: $PATH \
    && go version

FROM image AS onbuild

ONBUILD ARG GOARCH
ONBUILD ENV GOARCH=$GOARCH
ONBUILD ARG REPOSITORY
ONBUILD WORKDIR /go/src/${REPOSITORY}/
ONBUILD ARG CGO_ENABLED
ONBUILD ENV CGO_ENABLED=${CGO_ENABLED} \
    GO111MODULE=on
ONBUILD COPY go.mod .
ONBUILD COPY go.sum .
ONBUILD RUN go mod download
ONBUILD RUN go list -f '{{if (and ( not .Main) (not .Indirect))}}{{.Path}}@{{.Version}}{{end}}' -m all | xargs -tn 1 go get -v || true
ONBUILD COPY . .
ONBUILD ARG PACKAGE
ONBUILD ENV PACKAGE=${PACKAGE}
ONBUILD RUN /loader go build -v -o /app "${PACKAGE:-}"
