ARG IMAGE_NAME
FROM ${IMAGE_NAME}:temp AS image

RUN GOLANG_VERSION=1.24.8 \
    && DIGEST='6842c516ca66c89d648a7f1dbe28e28c47b61b59f8f06633eb2ceb1188e9251d' \
    && wget -O go.tgz "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
    && echo "${DIGEST} *go.tgz" | sha256sum -c - \
    &&	tar -C /usr/local -xzf go.tgz \
    && rm go.tgz \
    && echo PATH: $PATH \
    && RUN /bin/bash -uec rm -rf /tmp/.cache \
    && RUN /bin/bash -uec rm -rf /tmp/.config \
    && RUN /bin/bash -uec rm -rf /tmp/.wget-hsts \
    && go version

FROM image AS onbuild

ONBUILD ARG GOARCH
ONBUILD ENV GOARCH=$GOARCH
ONBUILD ARG REPOSITORY
ONBUILD WORKDIR /go/src/${REPOSITORY}/
ONBUILD ARG CGO_ENABLED
ONBUILD ENV CGO_ENABLED=${CGO_ENABLED} \
    GO111MODULE=on
ONBUILD COPY go.mod .
ONBUILD COPY go.sum .
ONBUILD RUN go mod download
ONBUILD RUN go list -f '{{if (and ( not .Main) (not .Indirect))}}{{.Path}}@{{.Version}}{{end}}' -m all | xargs -tn 1 go get -v || true
ONBUILD COPY . .
ONBUILD ARG PACKAGE
ONBUILD ENV PACKAGE=${PACKAGE}
ONBUILD RUN /loader go build -v -o /app "${PACKAGE:-}"
